version: "3"

volumes:
  tld_cache:
  rar_cache:

services:
  bootstrap:
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: /app/rdapd

  root:
    build: .
    volumes:
      - .:/app
      - tld_cache:/tmp/cache/tlds
      - rar_cache:/tmp/cache/registrars
    ports:
      - 8181:8080
    command: ["/app/bin/rootd"]
