app             = "rdap-bootstrap-server"
kill_signal     = "SIGINT"
kill_timeout    = 5
primary_region  = "lhr"
processes       = []

[experimental]
cmd             = ["/app/rdapd", "--port=443", "--tls"]

[build]
dockerfile      = "Dockerfile"

[deploy]
strategy        = "rolling"

[[services]]
internal_port   = 443

[services.concurrency]
type            = "requests"
hard_limit      = 512
soft_limit      = 128

[[services.ports]]
port            = 443

[services.http_checks]
grace_period    = "60s"
interval        = "30s"
timeout         = "5s"
tls_skip_verify = true
method          = "get"
path            = "/heartbeat"
protocol        = "https"
